// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bqbitlbwsskztiqpayws.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJxYml0bGJ3c3NrenRpcXBheXdzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY2NTY4ODUsImV4cCI6MjA2MjIzMjg4NX0.J1A5geE-KuheAUbiOu92dybZ7CI_5H9gglPsOlGkpu8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);